name: Asset Packer
description: Packs assets using asset_packer.exe

inputs:
  input:
    description: 'Input folder'
    required: false
    default: .
  config:
    description: 'Config file'
    required: false
    default: 'tools/packing.config'
  output:
    description: 'Output file name'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        & "${{ github.action_path }}\tools\asset_packer.exe" "${{ inputs.input }}" -c "${{ inputs.config }}" "${{ inputs.output }}"
      shell: pwsh
