name: Asset Packer
description: Packs assets using asset_packer.exe

inputs:
  input:
    description: 'Input folder'
    required: false
    default: .
  config:
    description: 'Config file'
    required: false
    default: ''
  output:
    description: 'Output file name'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        $configPath = if ("${{ inputs.config }}") { "${{ inputs.config }}" } else { "${{ github.action_path }}\tools\packing.config" }
        & "${{ github.action_path }}\tools\asset_packer.exe" "${{ inputs.input }}" -c "$configPath" "${{ inputs.output }}"
      shell: pwsh
